
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "php-pipeline"
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "meu-workshop-minha-vida", "kind": "DeploymentConfig"}]'
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/csmartins/workshop-php.git"
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfilePath: "Jenkinsfile.groovy"
