kind: "BuildConfig"
apiVersion: "v1"
metadata:
name: "workshop-pipeline"
annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "workshop-php", "kind": "DeploymentConfig"}]'
spec:
source:
    type: "Git"
    git:
    uri: "https://github.com/csmartins/workshop-php.git"
    ref: "master"
strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
    jenkinsfilePath: "Jenkinsfile.groovy"
